kind: Service
apiVersion: v1
metadata:
  name: maven-demo-service
spec:
  selector:
    app: maven-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-demo
  labels:
    app: maven-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-demo
  template:
    metadata:
      labels:
        app: maven-demo
    spec:
      imagePullSecrets:
      - name: local-registry
      containers:
      - name: maven-demo
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
